project:
  name: qs-workshop
  template: templates/main.template.yaml
  regions:
    - ap-southeast-1
    - eu-central-1
    - us-east-1
    - us-west-2
  parameters:
    AvailabilityZones: $[taskcat_getaz_2]
    EmailAddress: --override--
    WebserverCIDR: 0.0.0.0/0
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
tests:
  default:
    regions:
      - us-east-1
